### ISSUE TITLE
ASCOM won't detect my camera in APT or NINA

### ISSUE THREAD

**Issue by trooper1489** [totoantibes/LumixCameraAscomDriver#6]
Hi,
I am unable to connect my GH5 using this software. For some reason, it will not auto-detect my camera as it seems to be trying to connect using a different IP. When changing the IP to the one the camera shows in the settings I get an error (see image 1). I then tried to just fill out the settings anyway, but it doesn't connect. I tried connecting to the camera's wifi (no success) and I also tried connecting the camera through my home wifi (no success). 

Things I have tried, but haven't worked:
- Uninstalling the lumix ascom driver and reinsalling it (didn't work)
- Uninstalling the lumix ascom driver and trying an older one  (didn't work)
- Uninstalling and reinsalling ASCOM (didn't work)
- Uninstalling and reinsalling APT and NINA (didn't work)
- Resetting my GH5 (didn't work)
- Uninstalling and reinsalling microsoft visual c++ library (just in case, but didn't do anything)

I have also attached the camera logfile from APT just in case (at the bottom of the post).

Any help would be greatly appreciated. Thanks

![Image_1(Error)](https://user-images.githubusercontent.com/58759038/118485716-e790db00-b757-11eb-8728-4e28d9350e60.JPG)

[APT_Camera_1.log](https://github.com/totoantibes/LumixCameraAscomDriver/files/6493609/APT_Camera_1.log)

**Comment by totoantibes** [comment]
hi sorry this is causing you trouble.
Have you tried with the driver i posted just last night (7.0.3)?  it should pop an info box in case it does not find a lumix camera in the network.  even with that there is an issue that i cannot get rid of. the resolution of the camera needs to be changed  once and back to the proper resolution from the setupform. 
the error you are showing is typical of the form not registering all the values  in the fields. again please make sure you manually select the fields from the box. this is true only for the connect.  
I will have to solve this annoying issue but i dont really master VB...

**Comment by trooper1489** [comment]
Hi, thanks for the quick response. 
So I was able to get it to connect tonight, by manually imputing the camera's IP (which is strange as I tried doing that last night, but I was getting an error, but it works now, so who knows). But now APT says that it is unable to read the image file, even though it is set to JPG and I have set up a temp path. However, when I set the Transfer Format to Tumb it works, but the image is black and white in APT, but it is colour in NINA. Is this normal?

Sorry for all of this, I'm kind of new to this.
Thanks

**Comment by totoantibes** [comment]
(which version of the driver are you using?)

for discovery of camera IP address best (failsafe) is to :
1) connect the camera to an AP (home or phone)
2) trigger the camera into remote control via an APP (on phone)
3) then launch the driver from the PC connected to the same AP.
this way you should be able to discover and fill in all the fields.

then, even though the camera is discovered manually select the resolution of the camera from the driver.
if this fails then i would question firewalls or other obstacles in the path between your PC and your camera. (e.g. set wifi as private network and not public on windows)

if JPG fails it is either that the resolution is wrong or the wifi network not good enough. if it is wrong then thumb would work because all the resolutions are equiv in thumb. If the file is too large in jpg (doubtful) then it would fail to DL over Wifi.

as for the color. in APT you can select before connecting in asco if the file is BAYER and what matrix. make sure you have RGGB selected. 

please let me know how you get on,

**Comment by trooper1489** [comment]
Thanks for all that info, it was a big help!

I'm using the latest version (7.0.3).

So it all seems to be working fine now. I did the steps you suggested above and it discovered the camera just fine. The images are now coming through in colour too.

I am now able to use both NINA and APT just fine.

Thanks
